### ISSUE TITLE
uninitialized constant Rodauth::Rails::Feature (NameError)

### ISSUE THREAD

**Issue by Halvanhelv** [janko/rodauth-rails#337]
Hi! @janko  I have `rails 8.0.1`, `ruby 3.3.6` and `SolidQueue`

when trying to send an email (for example during registration) an error appears asynchronously

`uninitialised constant Rodauth::Rails::Feature (NameError)`

but for example if try the same thing through the rails console everything works fine

I tried both version 1 and 2 of `rodauth-rails `

do you have any idea what it could be? Thanks

**Comment by janko** [comment]
I couldn't reproduce it in a fresh Rails 8 app with Solid Queue. Could you create a minimal Rails app reproducing the issue?

**Comment by Halvanhelv** [comment]
> Also, could you provide a full backtrace of the error? I believe setting `BACKTRACE=1` env variable when running the `bin/jobs` process should do it.

Unfortunately logs are not shown in console but they are shown in `mission_control-jobs `

```
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/inflector/methods.rb:290:in `constantize'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionmailer-8.0.1/lib/action_mailer/mail_delivery_job.rb:36:in `mailer_class'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionmailer-8.0.1/lib/action_mailer/mail_delivery_job.rb:41:in `handle_exception_with_mailer_class'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/rescuable.rb:94:in `call'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/rescuable.rb:94:in `rescue_with_handler'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/rescuable.rb:167:in `rescue_with_handler'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/execution.rb:53:in `rescue in perform_now'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/execution.rb:45:in `perform_now'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activerecord-8.0.1/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:40:in `block in instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `block in instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:39:in `instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activerecord-8.0.1/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:26:in `perform_now'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/logging.rb:32:in `block in perform_now'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/broadcast_logger.rb:241:in `method_missing'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/logging.rb:39:in `tag_logger'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/logging.rb:32:in `perform_now'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/execution.rb:29:in `block in execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:120:in `block in run_callbacks'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/railtie.rb:95:in `block (4 levels) in <class:Railtie>'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/reloader.rb:77:in `block in wrap'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/reloader.rb:74:in `wrap'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/railtie.rb:94:in `block (3 levels) in <class:Railtie>'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `instance_exec'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `block in run_callbacks'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:140:in `run_callbacks'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activejob-8.0.1/lib/active_job/execution.rb:27:in `execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/solid_queue-1.1.0/app/models/solid_queue/claimed_execution.rb:95:in `execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/solid_queue-1.1.0/app/models/solid_queue/claimed_execution.rb:61:in `perform'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/solid_queue-1.1.0/lib/solid_queue/pool.rb:23:in `block (2 levels) in post'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/solid_queue-1.1.0/lib/solid_queue/app_executor.rb:7:in `wrap_in_app_executor'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/solid_queue-1.1.0/lib/solid_queue/pool.rb:22:in `block in post'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
<internal:kernel>:187:in `loop'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/Users/user/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
```

**Comment by janko** [comment]
So, it's erroring when it's trying to resolve the mailer class. This doesn't make sense to me, because loading the mailer class shouldn't attempt to load Rodauth, everything should be lazy-evaluated. Do you have a standard Rodauth mailer? Were you able to reproduce the error in fresh Rails app?

**Comment by Halvanhelv** [comment]
> So, it's erroring when it's trying to resolve the mailer class. This doesn't make sense to me, because loading the mailer class shouldn't attempt to load Rodauth, that should only happen when a mailer method is called. Do you have a standard Rodauth mailer? Were you able to reproduce the error in fresh Rails app?

I tried repeating on a completely new rails 8 application, the error is the same

**Comment by janko** [comment]
Could you share one and tell me the reproduction steps? Maybe I did something differently.

**Comment by Halvanhelv** [comment]
> Could you share one and tell me the reproduction steps? Maybe I did something differently.

1) `rails new test_app`
2) `bin/rails solid_queue:install`
3) used [Single database configuration](https://github.com/rails/solid_queue?tab=readme-ov-file#single-database-configuration) for `solidqueue`
4) added `config.active_job.queue_adapter = :solid_queue`
5) `rails generate rodauth:install`
6) `rails generate rodauth:views`
7) `rails s`
8) `bin/jobs`

**Comment by janko** [comment]
Thanks, I didn't realize this was happening with the default mailer, now the error makes sense 👍🏻 I will push a fix shortly.
